In [1]:
pip install numpy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Program Files\Python\python.exe -m pip install --upgrade pip' command.


In [9]:
import numpy as np

arrobj01 = np.array([1,2,3,4])
print(arrobj01)

# arrobj02 = np.array([14,"Ganesh","Welcome",56,78],)#error for string
# print(arrobj2)

arrobj02=np.array([[1,2 ,3],[4,5,6]], dtype=int) #2D array
print("Size:",arrobj02.size)
#shape,dimension and datatypes are attributes of the matrix.
print("shape:",arrobj02.shape)
print("dimension:",arrobj02.ndim)


#3-d array
arrobj03=np.array([[[2,3],[4,5]],[[4,5],[5,6]],[[7,6],[6,8]]])
print("Size:",arrobj03.size)
print("shape:",arrobj03.shape)
print("dimension:",arrobj03.ndim)



[1 2 3 4]
Size: 6
shape: (2, 3)
dimension: 2
Size: 12
shape: (3, 2, 2)
dimension: 3


In [ ]:
import numpy as np

arr = np.array([
    [-1, 2, 0, 4],
    [4, -0.5, 6, 0],
    [2.6, 0, 7, 8],
    [3, -7, 4, 2.0]
])

print("First row:",arr[0])
print("First Row,Second Coloumn",arr[0],[1])
arr2 = arr[:2, ::2]
print("First 2 rows and alternate columns:\n", arr2)


arr3 = arr[[1, 1, 0, 3], [3, 2, 1, 0]]
print("Selected elements:", arr3)



First row: [-1.  2.  0.  4.]
First Row,Second Coloumn [-1.  2.  0.  4.] [1]
First 2 rows and alternate columns:
 [[-1.  0.]
 [ 4.  6.]]
Selected elements: [0. 6. 2. 3.]


In [ ]:

arrobj1 = np.array([
            [1, 2],
            [3, 4]])

arrobj2 = np.array([
           [4, 3],
           [2, 1]])

print(arrobj1+1)
arrobj3=arrobj1+arrobj2
print(arrobj3)

print(arrobj3-2)
print(arrobj3.dtype)

print(np.sqrt(arrobj2)) #math.sqrt is applied to only a single array,where as np.sqrt is for whole array
print(arrobj2.T)

[[2 3]
 [4 5]]
[[5 5]
 [5 5]]
[[3 3]
 [3 3]]
int64
[[2.         1.73205081]
 [1.41421356 1.        ]]
[[4 2]
 [3 1]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

arr2 = newarr.reshape(12,)
print(arr2)

arr2 = newarr.reshape(-1) #if you dont want to write 12 
print(arr2)


arr3D = newarr.reshape(3,2,2)
print(arr3D)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [20]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)
print("Concatenate:")

print(arr)

arr = np.stack((arr1, arr2), axis=1)
print("stack :")

print(arr)


arr = np.hstack((arr1, arr2))
print("Hstack:")

print(arr)




Concatenate:
[[1 2 5 6]
 [3 4 7 8]]
stack :
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
Hstack:
[[1 2 5 6]
 [3 4 7 8]]


In [24]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 2)

print(newarr)

for arr1 in newarr:
    print(arr1)

[array([1, 2, 3]), array([4, 5, 6])]
[1 2 3]
[4 5 6]


In [27]:
arr = np.array([1, 2, 3, 4, 5, 6])

x=np.where(arr==1)
print(x)


arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)


(array([0]),)
[41 43]


In [ ]:
# arr=np.arrange([10,100, 5])
# print(arr)

np.zeros((3,4))
np.ones((2,3,4),dtype=np.int16)
arr.fill(0)
print(arr)

[0 0 0 0]


In [33]:
import time

# Loop - based operation
my_list = list(range(1000000))
start_time_loop = time.time()
result_loop = []
for num in my_list:
    result_loop.append(num * 2)
end_time_loop = time.time()
loop_time = end_time_loop - start_time_loop

# Vectorized operation
my_array = np.array(my_list)
start_time_vectorized = time.time()
result_vectorized = my_array * 2
end_time_vectorized = time.time()
vectorized_time = end_time_vectorized - start_time_vectorized

print(f"Time taken by loop: {loop_time} seconds")
print(f"Time taken by vectorized operation: {vectorized_time} seconds")

Time taken by loop: 0.1662921905517578 seconds
Time taken by vectorized operation: 0.00200653076171875 seconds
